openapi: 3.0.0
info:
  title: booking_service
  version: "1"
paths:
  /auth/signin:
    post:
      operationId: authAuthenticateUser
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthDto'
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /auth/signup:
    post:
      operationId: authRegisterUser
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        "201":
          description: ""
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /schedule/get_all_trips:
    get:
      operationId: scheduleGetAllTrips
      tags:
        - schedule
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TripScheduleDto'
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /schedule/get_trips/{departure}/{arrival}/{trip_date}:
    get:
      operationId: scheduleGetTrips
      tags:
        - schedule
      parameters:
        - in: path
          name: departure
          required: true
          schema:
            type: string
        - in: path
          name: arrival
          required: true
          schema:
            type: string
        - in: path
          name: trip_date
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TripScheduleDto'
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /booking/book_ticket:
    post:
      operationId: bookingBookTicket
      tags:
        - booking
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: trip_schedule_id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: ""
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /tickets/get_all_tickets/{user_id}:
    get:
      operationId: ticketsGetAllTickets
      tags:
        - tickets
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TicketDto'
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /tickets/delete_ticket/{ticket_id}:
    delete:
      operationId: ticketsDeleteTicket
      tags:
        - tickets
      parameters:
        - in: path
          name: ticket_id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: ""
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /admin/get_all_users:
    get:
      operationId: adminGetAllUsers
      tags:
        - admin
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /admin/delete_user/{user_id}:
    delete:
      operationId: adminDeleteUser
      tags:
        - admin
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: ""
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /admin/create_user:
    post:
      operationId: adminCreateUser
      tags:
        - admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        "201":
          description: ""
        "400":
          description: Service will return this if parameters are not provided or couldn't be parsed correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        "404":
          description: Service will return this if the endpoint is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Service will return this if unexpected internal error happens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    LoginDto:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    RegisterDto:
      type: object
      required:
        - first_name
        - last_name
        - phone
        - username
        - email
        - password
      properties:
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
    AuthDto:
      type: object
      required:
        - token
        - type
        - id
        - first_name
        - last_name
        - phone
        - username
        - email
        - roles
      properties:
        token:
          type: string
        type:
          type: string
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
        username:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            type: string
    UserDto:
      type: object
      required:
        - id
        - first_name
        - last_name
        - phone
        - username
        - email
        - password
        - roles
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleDto'
    CarDto:
      type: object
      required:
        - id
        - number
      properties:
        id:
          type: integer
          format: int64
        number:
          type: string
    RoleDto:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    TripDto:
      type: object
      required:
        - id
        - departure
        - arrival
        - trip_date
      properties:
        id:
          type: integer
          format: int64
        departure:
          type: string
        arrival:
          type: string
        trip_date:
          type: string
          format: date
    TripScheduleDto:
      type: object
      required:
        - id
        - departure_time
        - arrival_time
        - fare
        - available_seats
        - trip_detail
        - car_detail
      properties:
        id:
          type: integer
          format: int64
        departure_time:
          type: string
        arrival_time:
          type: string
        fare:
          type: integer
          format: int32
        available_seats:
          type: integer
          format: int32
        trip_detail:
          $ref: '#/components/schemas/TripDto'
        car_detail:
          $ref: '#/components/schemas/CarDto'
    TicketDto:
      type: object
      required:
        - id
        - passenger
        - trip_schedule
      properties:
        id:
          type: integer
          format: int64
        passenger:
          $ref: '#/components/schemas/UserDto'
        trip_schedule:
          $ref: '#/components/schemas/TripScheduleDto'
    BadRequestError:
      type: object
      required:
        - message
        - location
      properties:
        message:
          type: string
        location:
          $ref: '#/components/schemas/ErrorLocation'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      type: object
      required:
        - path
        - code
      properties:
        path:
          type: string
        code:
          type: string
        message:
          type: string
    ErrorLocation:
      type: string
      enum:
        - query
        - header
        - body
    NotFoundError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    InternalServerError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
